### PR TITLE
fix Ubuntu 22.04 GitHub Actions

### PR DESCRIPTION
**Pull request by ulmus-scott**
First, edit `mythplugins/configure` to enable building MythNetvision.  Then, fix the dependencies in the workflow `.yml` file.

##### Checklist

- [x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

### CODE REVIEW

**Comment by ulmus-scott** [comment]
I would like comment on the Python oauth vs oauthlib because more may need to be changed to work on Ubuntu 22.04.  That is, it compiles the C++ MythNetvision, but the Python component may not work.

`git grep -nE oauth` seems to suggest that only vimeo uses it.

**Comment by stuarta** [comment]
The python3-oauth package should be available to ubuntu-22.04.
Issue opened with github

https://github.com/actions/virtual-environments/issues/5895

**Comment by stuarta** [comment]
Superceded by https://github.com/MythTV/mythtv/commit/fb9457e9aa4de597c2bcd17aec3bfbe6f6da1bbf

**Comment by stuarta** [comment]
No they are not. Strictly speaking I could have completely left out that package. I believe mythnetvision needs updating to a different python oauth package. python3-oauthlib seems to be the favoured replacement. The other option is also unmaintained

**Pull request closed without merging**
