### PR TITLE
configure: enable optimizations, use system libudfread if available

### PR DESCRIPTION
**Pull request by ulmus-scott**
A crude first pass at enabling optimizations (`-O2`) for C++ files.  See: https://github.com/MythTV/mythtv/issues/406

Also, some minor cleanup in configure.

If pkg-config finds libudfread, use it.  It is probably better to remove it and libbluray and in configure git clone and use their actual configure scripts.

Version 1.1.1 is because V 1.1.0 had pkg-config as udfread.  Also, https://pkgs.org/search/?q=udfread doesn't list many, <s>which might mean it is packaged as part of libbluray (my guess).</s> Some systems lack packages for libudfread.

@linuxdude42 https://github.com/MythTV/mythtv/commit/60ae2ac4647e68b059820fb77d5be0cb724f483d#diff-fb1929a0befb6d7e932cde30a73b5f0bcbb897b046b9a0d7b833c9523efd6c31R6993 should this be `$gxx_major_version -lt 11`?  Using `-isystem` to add the include paths for Qt, etc., is probably a better solution, however.

##### Checklist

- [x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x] code compiles successfully without errors
- [x] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [x] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

### CODE REVIEW

**Comment by garybuhrmaster** [comment]
> If pkg-config finds libudfread, use it. It is probably better to remove it and libbluray and in configure git clone and use their actual configure scripts.

One cannot "git clone" during builds.  One cannot presume network connectivity for building software (many distributions explicitly disable network connections during builds to insure reproducibility).

**Comment by ulmus-scott** [comment]
> One cannot "git clone" during builds. One cannot presume network connectivity for building software (many distributions explicitly disable network connections during builds to insure reproducibility).

OK.  I was only floating that idea since both libudfread and libbluray are unmodified copies in the repository and `git clone` is used in https://github.com/MythTV/mythtv/blob/master/platform/win32/w64-mingw32/MythBuild_MXE.sh (found while `git grep`ping).

**Comment by linuxdude42** [comment]
On Sun, 2021-11-07 at 11:35 -0800, ulmus-scott wrote:
> > One cannot "git clone" during builds. One cannot presume network
> > connectivity for building software (many distributions explicitly
> > disable network connections during builds to insure
> > reproducibility).
> OK. I was only floating that idea since both libudfread and libbluray
> are unmodified copies in the repository and git clone is used in
> https://github.com/MythTV/mythtv/blob/master/platform/win32/w64-mingw32/MythBuild_MXE.sh
> (found while git grepping).

That's initial support for a mingw32/64 port. At some point I hope that
ends up like the android port, where you only have compile the
libraries once, and then can compile MythTV as often as you want.

David

**Comment by garybuhrmaster** [comment]
> That's initial support for a mingw32/64 port. At some point I hope that ends up like the android port, where you only have compile the libraries once, and then can compile MythTV as often as you want. David

Feels like that WIP should eventually end up in the packaging repo (like the android build port). and, in addition, ideally, all the steps to build a builder would be in ansible (reproducible builders and builds are the best).

**Pull request merged**
