### PR TITLE
Devel/python3

### PR DESCRIPTION
**Pull request by rcrdnalor**
Add compatibility to python3 of MythTV's Python Bindings.

Note: This does not include files from:
 - services_api
 - ttvdb
 - mythnetvision
 - mythmusic

### CODE REVIEW

**Comment by rcrdnalor** [comment]
Note: The announced changes are based on tests from repository at
https://github.com/rcrdnalor/MythTV-Python-Tests

**Comment by rcrdnalor** [comment]
reopened.

**Comment by rcrdnalor** [comment]
Tracked at #13475 in MythTV's trac system at
https://code.mythtv.org/trac

**Comment by rcrdnalor** [comment]
I found additional incompatibilities to python3:
The last patch fixes #12243 as well and the testcases verified,
that #12245 cannot be reproduced anymore.
See file 'test_Dataheap_VideoGrabber_001.py' from my repo
https://github.com/rcrdnalor/MythTV-Python-Tests

Please update your local test environment to include these patches.

**Comment by rcrdnalor** [comment]
There are still open issues:
 - the `__mataclass__` property is deprecated in python3
 - the `__repr__` method returns a `str` type in python2 and python3, which means conversion to `utf-8` for python2, only

**Comment by rcrdnalor** [comment]
I added compatibility to python3 for the `__repr__` methods.

The interactive python shell should now work like in python2:

  $ python3
  Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
  >>> from MythTV import MythDB, Recorded
  >>> db = MythDB()
  >>> rec = Recorded((3002, 20190622125000), db = db)
  >>> rec     -----> this calls __repr__ under the hood. 
  <Recorded 'Reisezeit - Kurztrip','2019-06-22 12:50:00+02:00' at 0x7fcdb0faabe0>'
  >>> 

instead of returning an error like  `TypeError: __repr__ returned non-string .....`

Thanks to Bill pointing me to the right direction ( in ticket 13300 ).

**Comment by rcrdnalor** [comment]
I fixed the last known incompatibility to python3 related to 'metaclasses'.

The tests can be found on my repo:
https://github.com/rcrdnalor/MythTV-Python-Tests

With the last commit from this pull request 182, the python bindings at 'mythtv/bindings/python' have no open issues so far.

Please update your test environment.

**Comment by rcrdnalor** [comment]
I updated this pull request with a fix for #13300 an a
patch to silence a warning of python3 on exit() on some occasions.

Tests have been added to my testing repository at
https://github.com/rcrdnalor/MythTV-Python-Tests

Please give it a try and update your test installations.
See https://www.mythtv.org/wiki/Python3_Conversion  

Note: this pull request now closes the following tickets:
#12243 	Python Bindings failing with new inetrefid changes
#12245 	mythvidexport fails when there are non ascii characters in actor names.
#13320 	Python bindings not reconnecting to database after a long pause.
#12365 	Patch: Update Perl and Python bindings proto version and token
#13299 	Python Bindings fail to calculate date-time object
#13300 	Python Bindings enhancemts according to latest MythTV protocol (91)

**Comment by billmeek** [comment]
Roland, please reopen if you disagree.

**Pull request closed without merging**
