### PR TITLE
Ttvdb api v2

### PR DESCRIPTION
**Pull request by mspieth**
Thank you for contributing to MythTV.

As many of our developers do not visit GitHub it is important to track
all contributions at our central ticket tracker over at code.mythtv.org

To prevent your contributions being overlooked please create a new ticket
there and refer to this pull request. (Bonus points for linking to the
ticket in the pull request, too. It helps us noticed potentially overlooked
pull requests due to missing tickets.)

https://code.mythtv.org/trac/wiki/TicketHowTo
https://code.mythtv.org/trac/newticket

### CODE REVIEW

**Comment by frederickjh** [comment]
[MythTV Trac Ticket #13084 URL](https://code.mythtv.org/trac/ticket/13084>) that goes with this pull request.

**Comment by bennettpeter** [comment]
I have merged this pull request into master. Please can somebody close it.

**Comment by mspieth** [comment]
Merged

**Comment by amessina** [comment]
@bennettpeter are there plans to merge this to fixes/29 as the cutoff is approaching?

**Pull request closed without merging**
