### PR TITLE
Add metadata lookup by timestamp to tmdb3tv.py

### PR DESCRIPTION
**Pull request by SteveErl**
This change adds **lookup by timestamp** syntax options:

```
    tmdb3tv.py -N <title> <date time>
    tmdb3tv.py -N <inetref> <date time>
```

For example:

```
tmdb3tv.py -N "The Blacklist" "2021-01-29 19:00:00"
<?xml version='1.0' encoding='UTF-8'?>
<metadata>
  <item>
    <title>The Blacklist</title>
    <subtitle>Elizabeth Keen</subtitle>
    <description>As Red and the task force search for Liz, she sets a new plan in motion that has catastrophic consequences.</description>
    <season>8</season>
    <episode>4</episode>
    <inetref>46952</inetref>
    <collectionref>46952</collectionref>
    <language>en</language>
    <releasedate>2021-01-29</releasedate>
    ...
  </item>
</metadata>
```
In the above example, by specifying the start of the recording time, we were able to acquire the Season, Episode, Subtitle, and Description. Without this new capability, the -N invocation would fail, and would be followed by a -M invocation, which would provide only a generic description of the TV series.

Please note that the TMDB database only stores the date, and not the time, of the initial airing. The match cannot be as precise as in a TvMaze lookup, which has access to the date, time, and timezone. If there are multiple episodes aired on a single date, the TMDB script will generate a list with all the episodes matching the date in the given timestamp.

Resolves: #700

##### Checklist

- [x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [x] documentation added/updated/removed where necessary
- [x] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

### CODE REVIEW

**Review by rcrdnalor — COMMENTED** [review]
A datetime or date object without an associated timezone is ambiguous.
Please check with themoviedb.com the timezone of ''air_date' of a given episode
and report back.
If the timezone is 'UTC' than the API is not in accordance with the tvmaze grabber.

**Comment by SteveErl** [comment]
@rcrdnalor : It took quite a bit of digging, but I did find confirmation that all the dates are stored in UTC. I'll update my  code to adjust the date based on the users timezone.

While trying to come up with a test case, I discovered that there's a bug in our tvmaze.py script. When doing a lookup by timestamp, it fails to get specific episode information when the timezone adjusted starting time is shortly after midnight. I'll open a new issue to fix this bug.

**Comment by SteveErl** [comment]
@rcrdnalor : The documentation for TMDB3 is incredibly vague and inconsistent about timezones. There is only one API command where they let you specify a timezone. The **_GET /tv/airing_today_** command. In the API documentation for that command, they say the query defaults to the US Eastern Time zone (UTC-05:00), a.k.a America/New_York.

In 2018, one user asked about UTC:
https://www.themoviedb.org/talk/5b5793520e0a2673dc0402cb
**Question**: All dates ** release_date, first_air_date, last_air_date, air_date** tmdb provides in UTC. Am I right?
**Staff Response**: You are correct, all UTC.

But, this isn't true, and somebody pointed it out in 2020.
https://www.themoviedb.org/talk/5e7f5e84a275020016eec583
**Staff Response**: It's not assumed to be UTC, it's assumed to be 00:00 in the timezone of the original airing network.

From my testing this still seems to be wrong for shows starting near midnight. I have a recording of an NBC late night talk show which starts at 11:35pm in the US Central timezone, which means it's 00:35am of the next day in the US Eastern timezone, which is considered the timezone of the original airing network. When I shift the recording time from 11:35pm to 00:35am, and lookup by date, TMDB returns the metadata for the next day's episode, which is wrong. To further complicate things, the broadcast networks re-broadcast the shows 2 hours later for the Mountain and Pacific timezones.

Due to these sorts of issues, the TvMaze API has a special care policy.
https://www.tvmaze.com/faq/15/episodes
`The time should be in the local timezone where the episode premiered. If the show's network operates in multiple timezones, the earliest timezone should be used; for example in the United States this is Eastern time. Special care should be taken when episodes air at or after midnight. To ensure that the episode airdates on TVmaze are in line with the dates used by TV guides and listings worldwide, episodes that start airing at or after midnight but before 5:00 are considered part of the previous day. For example, if an episode airs after midnight between Monday the 1st and Tuesday the 2nd, the airdate should be set to the 1st; even though technically the proper date would be the 2nd. (API users should take note that the property "airdate" uses the date as described here; while "airstamp" uses the technically correct date).`

The bug in tvmaze.py, I mentioned in the previous comment, was that it didn't account for this special care policy. I'm tempted to apply the same fix to the TMDB3 script, even though they never specify that they are following the same sort of policy.

**Comment by SteveErl** [comment]
I haven't mixed anything up. I had noticed that tmdb3.py is susceptible to errors when the starting time of a show slips past midnight. Before my latest commit:
```
$ TZ=America/Chicago /usr/share/mythtv/metadata/Television/tmdb3tv.py -l en -a US -N "Late Night With Seth Meyers" "2023-01-25 23:37:00"
<?xml version='1.0' encoding='UTF-8'?>
<metadata>
  <item>
    <title>Late Night with Seth Meyers</title>
    <subtitle>Colin Quinn, Gabrielle Union</subtitle>
    <description>Colin Quinn, Gabrielle Union</description>
    <season>10</season>
    <episode>53</episode>
    <inetref>61818</inetref>
    <collectionref>61818</collectionref>
    <language>en</language>
    <releasedate>2023-01-25</releasedate>
    <runtime>41</runtime>
    <categories>
      <category name="Talk"/>
    </categories>
    <people>
      <person name="Seth Meyers" character="Self - Host" department="Actors" job="Actor" url="http://www.themoviedb.org/people/62856" thumb="http://image.tmdb.org/t/p/original/nCcvpJFHWYHfu5oPxTOyA1uSdqA.jpg"/>
    </people>
    <images>
      <image type="fanart" url="http://image.tmdb.org/t/p/original/5AkPhazx8F0Ht74CUdJU03vNzBi.jpg" thumb="http://image.tmdb.org/t/p/w300/5AkPhazx8F0Ht74CUdJU03vNzBi.jpg"/>
    </images>
  </item>
</metadata>
```

When the same show is recorded in Eastern timezone we get:

```
$ TZ=America/New_York /usr/share/mythtv/metadata/Television/tmdb3tv.py -l en -a US -N "Late Night With Seth Meyers" "2023-01-26 00:37:00"
<?xml version='1.0' encoding='UTF-8'?>
<metadata>
  <item>
    <title>Late Night with Seth Meyers</title>
    <subtitle>Alex Wagner, Bowen Yang</subtitle>
    <description>Alex Wagner, Bowen Yang</description>
    <season>10</season>
    <episode>54</episode>
    <inetref>61818</inetref>
    <collectionref>61818</collectionref>
    <language>en</language>
    <releasedate>2023-01-26</releasedate>
    <runtime>41</runtime>
    <categories>
      <category name="Talk"/>
    </categories>
    <people>
      <person name="Seth Meyers" character="Self - Host" department="Actors" job="Actor" url="http://www.themoviedb.org/people/62856" thumb="http://image.tmdb.org/t/p/original/nCcvpJFHWYHfu5oPxTOyA1uSdqA.jpg"/>
    </people>
    <images>
      <image type="fanart" url="http://image.tmdb.org/t/p/original/5AkPhazx8F0Ht74CUdJU03vNzBi.jpg" thumb="http://image.tmdb.org/t/p/w300/5AkPhazx8F0Ht74CUdJU03vNzBi.jpg"/>
    </images>
  </item>
</metadata>
```
In this case, the correct metadata for the show was the American/Chicago result of Season 10, Episode 53 even though America/New_York is considered the timezone of the original airing network. Nowhere in the TMDB documentation do they tell you that a show starting at midnight or shortly after should be credited to the prior date, but that's what they have implemented in their database.

In thankfully clear explanation in a different TV listings API (TvMaze) they mention that they had to adjust the airdate assigning policy  "to ensure that the episodes ... (in the database) ... _**are in line with the dates used by TV guides and listings worldwide**_, episodes that start airing at or after midnight but before ... (**cutoff**)... are considered part of the previous day. The critical part of this statement is that they point out that TV guides and listings worldwide do this sort of shifting when assigning an airdate to an episode.

For TvMaze, **cutoff** is 5am. For TMDB, they don't tell us. I had one example, "Late Night With Seth Meyers", revealing that a show between midnight and 1am is assigned the previous date. It's hard to find other TV shows with new episodes starting at or after 1am, but I tracked down "Last Call with Carson Daly" which used to air at 1:35am in New York. There's only metadata for one episode (Season 13, Episode 57) in the TMDB database, but we can compare that to the same episode in the TvMaze database. Doing so shows that **cutoff** for TMDB is at least 2am.

I haven't found any other daily TV show starting between 2am and 5am to further refine the **cutoff** value for TMDB. Since the TvMaze developers are more knowledgeable than me on the subject of 'dates used by TV guides and listings worldwide', and far more  knowledgeable than the TMDB developers, I choose to follow their example. This provides the right results for all the late night shows I've tested.

**Comment by rcrdnalor** [comment]
Neither the API from themoviedb.org nor the forum specify how the `air_date` shall be used.
Over the world, there is a large community of themoviedb which fills in data for current and past movies and series.
It is likely, that these data are wrong because of missing rules. 
In contrast to tvmaze, themoviedb is used worldwide from may users. TVmaze is only useful in North-America, because it offers only a limited set of data.
The search for an episode of a tv-series by given timestamp is optional in MythTV, not required.
I repeat my previous words:
In case themoviedb.org does not provide correct data for the air-date, it is better to not provide this feature ("search for air-date")
than implementing any heuristic workarounds.
I do not want to discuss this further.

**Pull request closed without merging**
