### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by dfdario**
While checking the Italian translation status I found three new sentences from my last update from yesterday so I released a new one

Thank you for contributing to MythTV!

Please review the checklist below to ensure that your contribution
to MythTV is ready for review by our developers.

It is helpful to regularly rebase your pull request to ensure changes
apply cleanly to the current MythTV development branch.

##### Checklist

- [ ] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [ ] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [ ] code compiles successfully without errors
- [ ] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [ ] documentation added/updated/removed where necessary
- [ ] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

### CODE REVIEW

**Comment by knowledgejunkie** [comment]
Thank you @dfdario !

**Comment by kmdewaal** [comment]
@knowledgejunkie this is now in v35-pre, need to backport this to v34 before @linuxdude42 makes the final cut....

**Comment by knowledgejunkie** [comment]
@kmdewaal Thank you for the nudge. I'd already cherrypicked it but was called away before pushing to fixes/34. Should be sorted now!

**Comment by knowledgejunkie** [comment]
Any further translation updates can go in future v34 point releases

**Pull request merged**
