### PR TITLE
Update FFmpeg to version 7.1

### PR DESCRIPTION
**Pull request by ulmus-scott**
##### Checklist

- [x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x] code compiles successfully without errors
- [x] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [x] documentation added/updated/removed where necessary
- [x] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

# Commits

The commits in order are:

FFmpeg reversions
https://github.com/MythTV/mythtv/pull/923

Eliminate usage of internal FFmpeg headers
https://github.com/MythTV/mythtv/pull/931

mpegts-mythtv harmonization
https://github.com/MythTV/mythtv/pull/927

Changes to make MythTV compile with FFmpeg 7.1:
```
6716364c61 cmake/configure: remove references to unsupported crystalhd
d271e34a86 constify AVIOContext::write_packet buf parameter
1304aee821 constify AVIOContext::write_packet buf parameter (plugins)
84c178159a Use AVFrame::best_effort_timestamp
```

Update to FFmpeg 7.1:
```
976ab94b53 update FFmpeg to version 7.1
f8928e842c add ffmpeg_update_instructions.md
```

Cleanup after update:
```
807ef793aa remove support for LIBAVFORMAT_VERSION_MAJOR < 61 (plugins)
6c4c2684e2 remove support for LIBAVFORMAT_VERSION_MAJOR < 61
5098f349fb fix TestMusicMetadata::test_mp4()
```

Silence new FFmpeg deprecation warnings:
```
383aca2ea1 libmythtv/io/mythavformatwriter.cpp: silence AVCodec deprecation warnings
d43d574a59 replace deprecated av_stream_get_side_data()
93a9bc4d3c replace deprecated av_fft API with av_tx
ae3825083a replace deprecated AVFrame::interlaced_frame, top_field_first, and key_frame
7849f3029b mytharchivehelper.cpp: replace deprecated AVFrame::key_frame
e4e850b5e7 replace deprecated av_fft API with av_tx (mythmusic)
```

Other cleanup commits made while investigating:
```
dc03e8d08b remove DecoderBase::m_getRawFrames and m_getRawVideo
8f08f60856 remove unused no-op functions from DecoderBase
ca0e299060 mythaverror: add new functions returning std::string
b22e19e8b9 split libmyth/mythavframe.h from libmyth/mythaverror.h
7fe6c88070 create AvFormatDecoder::do_av_seek()
31af3ce5e2 remove unused GetAVTimeBaseQ()
552e90b564 MythMediaBuffer::WaitForAvail(): simplify return logic
```

# Testing

@kmdewaal , I have reverted your fix regarding blocking with VDPAU referencing https://trac.ffmpeg.org/ticket/9532.  Could you test if it is still an issue and update the FFmpeg trac as needed?

I have tested with my various Video samples and US OTA ATSC recordings and everything appeared to work the same.  I do not have any hardware acceleration set up, so I could not test with that.

Testing with hardware acceleration or other source types would be helpful.

## Quirks in `master` I may look into more

AvFormatDecoder::GetFrame() log spam every ~100μs: `decoding error End of file` if paused near end of file. I can sometimes trigger this with Video files when skipping by 1 second near the end while paused.

The seeking code for Videos is very fragile, I suspect multithreading issues.
Sometimes either seek forward or backward does nothing and gives the following error in the log:
`AFD: av_seek_frame(ic, -1, 13449820978, 0) -- error`
Some further investigation revealed the error code to be -1, which FFmpeg thinks
is EPERM.

For a short (~16s) audio only file I created, skipping backwards usually causes playback to exit instead of skipping.

### CODE REVIEW

**Comment by warpme** [comment]
Scott,
Per our conversation on ML about ffmpeg5->ffmpeg7 regression on n3450 with 2x vaapi deinterlacer: pls find 2 logs for playback of interlaced h264 recording. ffmpeg5 has working 2x DI while ffmpeg7 reports on osd "2x VAAPI Compensated" but visually i see 1x DI on screen
I was trying to catch diff between logs but failed to see meaningful diff :-(
[n3450-ffmpeg7-nok.log.zip](https://github.com/user-attachments/files/17504703/n3450-ffmpeg7-nok.log.zip)
[n3450-ffmpeg5-ok.log.zip](https://github.com/user-attachments/files/17504705/n3450-ffmpeg5-ok.log.zip)

**Comment by ulmus-scott** [comment]
@warpme I had made a typo in mythvaapiinterop.cpp which is fixed in the [first new commit](https://github.com/MythTV/mythtv/pull/950/commits/9972ac7ea38fade248855def4f9b8363d17e8179) and hopefully fixes the double rate VAAPI deinterlacing.

I did not see anything of interest in the logs either.

If the new commit doesn't work, try testing at https://github.com/MythTV/mythtv/pull/950/commits/93a9bc4d3c6ce4af346c4ed60da88c4cda80251b and, if that still doesn't work, at https://github.com/MythTV/mythtv/pull/950/commits/84c178159a71d8430d6780d3e9bc8f3399fcc9c0 before the FFmpeg update.

### Before merging I want to move some of the final commits earlier and squash some of them together.

**Comment by warpme** [comment]
Scott,

Current head works perfectly now!
Many thx fixing this.
I will start to use ffmpeg7.1 branch in production on x86 and aarch64 systems to see how stability, hw decoding for various codecs looks like.

**Comment by ulmus-scott** [comment]
Rebased onto master with a few commits reordered and squashed.

**Comment by bennettpeter** [comment]
I have rebased and merged into branch devel/ffmpeg-resync.

**Comment by kmdewaal** [comment]
Works OK for me. No regression found.

I do have a few ATSC3.0 recordings and they do play back with a lot of stuttering and complains about  the ac4 audio codec:
```
2024-12-22 21:44:08.963749 I  AFD: Using vaapi for video decoding
2024-12-22 21:44:08.963757 I  AFD: Opened codec 0x22025f40, id(hevc) type(Video)
2024-12-22 21:44:09.030591 W  avcodec_find_decoder fail for 86119
2024-12-22 21:44:09.030620 I  AFD: codec ac4 has 0 channels
2024-12-22 21:44:09.030644 W  avcodec_find_decoder fail for 86119
2024-12-22 21:44:09.030649 E  AFD: Could not find decoder for codec (ac4), ignoring.
```

With the current master there is not even an attempt to play the audio but the video plays smooth.

**Comment by ulmus-scott** [comment]
@kmdewaal , I have reverted your fix regarding blocking with VDPAU referencing https://trac.ffmpeg.org/ticket/9532.  Could you test if it is still an issue and update the FFmpeg trac as needed?

FFmpeg does not currently have a decoder for AC-4, but a raw muxer and demuxer were added so there is now AV_CODEC_ID_AC4, so it now recognizes the stream as AC-4 but can't decode it.

Is master also using vaapi hardware acceleration?  Is ffmpeg/7.1 repeatedly trying to find a decoder for AC-4?

**Comment by kmdewaal** [comment]
> @kmdewaal , I have reverted your fix regarding blocking with VDPAU referencing https://trac.ffmpeg.org/ticket/9532. Could you test if it is still an issue and update the FFmpeg trac as needed?

I do not have an Nvidia/VDPAU system running at the moment so I cannot test it right now. Possibly later. I am OK with having the fix reverted. 
> 
> FFmpeg does not currently have a decoder for AC-4, but a raw muxer and demuxer were added so there is now AV_CODEC_ID_AC4, so it now recognizes the stream as AC-4 but can't decode it.

Yes, I gathered as much. This should in principle make it possible to use audio pass-through for AC4 so that people with an  audio system that can decode AC4 can then use ATSC3.0.
> 
> Is master also using vaapi hardware acceleration? Is ffmpeg/7.1 repeatedly trying to find a decoder for AC-4?
The fragment log that I posted yesterday, with messages about not finding the ac4 decoder,  is repeated continuously, with intervals in the milliseconds.
Playback is done with vaapi hardware acceleration. This does work.

**Comment by bennettpeter** [comment]
I have reset branch devel/ffmpeg-resync and merged the updated pull request into devel/ffmpeg-resync.

**Comment by ulmus-scott** [comment]
@kmdewaal , I am not sure why ffmpeg/7.1 would have stuttery video playback or repeatedly try to find a decoder for AC-4.

Could you provide a more complete log with `-v playback:debug,audio:debug,libav:debug --logpath=/tmp`?

Could you also upload an ATSC 3.0 sample that is stuttering and repeatedly failing to find the (non-existent) decoder?

**Comment by bennettpeter** [comment]
Therfe is a sample here, only a few seconds,
https://trac.ffmpeg.org/attachment/ticket/8349/atsc3.ts

I see the same thing that Klaas describes. I am using ffmpeg decoding, I do not have any accelerated video on my laptop, so it is doing ffmpeg decoding.

**Comment by ulmus-scott** [comment]
AvFormatDecoder::SeekReset() calls GetFrame() in a loop with a 1 ms delay.
GetFrame() calls StreamChangeCheck() which calls ScanStreams() which calls
MythCodecMap::GetCodecContext() to produce the log message
`avcodec_find_decoder fail for 86119` and then prints its own
`AFD: Could not find decoder for codec (ac4), ignoring.`.

However, breaking that loop does not effect the log messages.

Something is calling AutoSelectAudioTrack() repeatedly producing
```avformatdecoder.cpp:4204 (AutoSelectAudioTrack) - 0 available audio streams```.

I'm using FFmpeg software decoding and I get aborts with that sample:
```
Handling Aborted
Aborted (core dumped)
```

gdb shows that the assert at libavutil/imgutils.c:350 is failing, related to copying a video frame.

This resolves my aborts:
```
diff --git a/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp b/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
index 5cd8e3cb8d..09d022125a 100644
--- a/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
+++ b/mythtv/libs/libmythtv/decoders/avformatdecoder.cpp
@@ -4836,7 +4836,7 @@ bool AvFormatDecoder::GetFrame(DecodeType decodetype, bool &Retry)
                          avcodec_get_name(curstream->codecpar->codec_id))
                         .arg(curstream->codecpar->codec_id));
                 // Process Stream Change in case we have no audio
-                if (codec_type == AVMEDIA_TYPE_AUDIO && !m_audio->HasAudioIn())
+                if (false && codec_type == AVMEDIA_TYPE_AUDIO && !m_audio->HasAudioIn())
                     m_streamsChanged = true;
             }
             av_packet_unref(pkt);
```

However, I still get a long list of quickly repeating
```

2024-12-23 18:46:12.697309 W [308931/309011] Decoder mythavutil.cpp:310 (GetCodecContext) - avcodec_find_decoder fail for 86119
2024-12-23 18:46:12.697312 E [308931/309011] Decoder avformatdecoder.cpp:4832 (GetFrame) - AFD: No codec for stream index 1, type(Audio) id(ac4:86119)
```

which then stops and then I get a long list of
```
avformatdecoder.cpp:4204 (AutoSelectAudioTrack) - 0 available audio streams
```

and then the two mix together.

Video playback is not stuttery.  I'll have to look into this more.

**Comment by ulmus-scott** [comment]
`mythfrontend -v playback:debug,audio:debug --logpath=/tmp` now only shows one call to ScanStreams() and thus one set of log messages about AC-4 since AV_CODEC_ID_AC4 is now ignored.

**Comment by bennettpeter** [comment]
@ulmus-scott  

I plan to merge the stuff that is already in devel/ffmpeg-resync next week as long as problems are not reported. Those have been tested and are stable, with the exception of the ATSC3 problem. AC-4 audio does not work with the existing system anywway.

It looks like the new commits are for MytTV not ffmpeg. I will merge them separately after ffmpeg has been merged into master.

**Comment by ulmus-scott** [comment]
@bennettpeter OK, this was probably not the pull request to do that new clean up, but I could create a version of https://github.com/MythTV/mythtv/pull/950/commits/d35d23c2f749026f0dd8f9bc0d7aed48767df2f0 that does not depend on the rest of the new changes if desired.

**Comment by bennettpeter** [comment]
I am ready to merge the pull request, but now there are conflicts due to changes applied in the interim. I am unsure of how to fix them. I get a conflict in libs/libmyth/audio/freesurround_decoder.cpp . Please rebase on to master so that I can merge.

**Comment by ulmus-scott** [comment]
David Hampton changed the order in `freesurround_decoder.cpp`, but the change after the commit was still correct.

The changes that were not in `devel/ffmpeg-resync` were removed and will be in a new pull request after this merges.

**Comment by bennettpeter** [comment]
I have rebasewd and merged this pull request.

**Comment by ulmus-scott** [comment]
@bennettpeter The commits that I removed from this are now at https://github.com/MythTV/mythtv/pull/1009

**Pull request closed without merging**
