### PR TITLE
Remove relinquishing of the D-Bus sleep inhibition token upon reset.

### PR DESCRIPTION
**Pull request by Dadeos**
Thank you for contributing to MythTV!

Please review the checklist below to ensure that your contribution
to MythTV is ready for review by our developers.

It is helpful to regularly rebase your pull request to ensure changes
apply cleanly to the current MythTV development branch.

##### Checklist

- [x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x] code compiles successfully without errors
- [x] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [x] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

### CODE REVIEW

**Comment by Dadeos** [comment]
Currently, `MythScreenSaverDBus::Reset()` calls `MythScreenSaverDBus::Restore()`:
https://github.com/MythTV/mythtv/blob/e71ca1204cb50100a95169b22a6cc608c398e9e4/mythtv/libs/libmythui/platforms/mythscreensaverdbus.cpp#L157-L160 which has the effect of relinquishing any tokens obtained for the purpose of preventing the system from sleeping.

As far as I can tell, the intended purpose of `MythScreenSaver::Reset()` is to request an extension to the inhibition, rather than relinquishing it. It appears that `MythScreenSaver::Reset()` is called from various places in response to events such as key-presses - the primary calls I observed originated from `MythCECAdapter::HandleKeyPress(…)`:
https://github.com/MythTV/mythtv/blob/1acc7ed4e07619d08b056016776a6ee352176444/mythtv/libs/libmythui/devices/mythcecadapter.cpp#L646 - which would be a requirement for interacting with countdown-timer based implementations.

However, the current D-Bus implementation has the effect that, sleep is inhibited whilst watching TV until such time as `MythScreenSaver::Reset()` is triggered (e.g. by pressing a key on the CEC linked remote control) after which the system will sleep - once the configured _idle_ period has elapsed.

**Comment by kmdewaal** [comment]
First, thanks for the excellent quality of your PR. Good reasoning and well documented.

I also do not really know what the Reset function should do but it could just be that the Reset function should be identical for the different platforms that are supported.
For OSX the Reset() function is empty.
https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythui/platforms/mythscreensaverosx.cpp#L22

For Android the Reset() function is empty.
https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythui/platforms/mythscreensaverandroid.cpp#L83

For DRM the Reset() function is empty.
https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythui/platforms/mythscreensaverdrm.cpp#L41

For Wayland the Reset() function does a Restore, just like the DBus Reset() discussed in this PR.
https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythui/platforms/mythscreensaverwayland.cpp#L78

For X11 the Reset() function does a lot which I do not all understand, but it does not a restore.
https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythui/platforms/mythscreensaverx11.cpp#L274

The current Wayland implementation is at the moment somewhat broken and also not widely used anyway. It could just be that the Reset() in the Wayland implementation is incorrect.

Conclusion: this PR looks good to me and will be merged. If anybody complains we can always reconsider.

**Comment by kmdewaal** [comment]
@Dadeos can you please state which problem has been solved by this pull request?

N.B. I kind of implicitly understood that in  your system the screensaver became active when it should not be, because the screensaver inhibit was removed by the reset. However, that is not stated explictly.
Given issue #1064 I do consider reverting this commit.

**Comment by Dadeos** [comment]
@kmdewaal: Your understanding is correct…
> However, the current D-Bus implementation has the effect that, sleep is inhibited whilst watching TV until such time as MythScreenSaver::Reset() is triggered (e.g. by pressing a key on the CEC linked remote control) after which the system will sleep - once the configured idle period has elapsed.

**Pull request merged**
