### PR TITLE
Break circular/cross dependency between libmythservicecontracts and libmyth

### PR DESCRIPTION
**Pull request by ulmus-scott**
This pull request has been split into several smaller ones:
- [x] miscutil cleanup
  - [x] https://github.com/MythTV/mythtv/pull/439
  - [x] https://github.com/MythTV/mythtv/pull/440
- [ ] https://github.com/MythTV/mythtv/pull/553
- [ ] https://github.com/MythTV/mythtv/pull/466
- [ ] move files
  - [ ] libmyth to libmythbase
    - [ ] https://github.com/MythTV/mythtv/pull/554
    - [ ] other files
  - [ ] libmyth to libmythui
    - [x] depends on https://github.com/MythTV/mythtv/pull/465
  - [ ] libmythtv to libmythbase
- [ ] mythcoreutil
- [ ] bump library ABI version

- [ ] update the doxygen architecture file

After refactoring MythContext into MythGUIContext, it will be able to move it and other UI files into libmythui.

libmyth will be left with almost exclusively the audio stuff.  At that point, it may make sense to move some of the video codec stuff from libmythtv into libmyth (possibly renamed to libmythcodec?).

Advice on how to reconnect the translations to their new position, would be appreciated.  (For later reference.  I dropped that change for now.)

Also, do you know why RecStatus is a QObject?  It is really an enumeration and some related functions (that should be in a namespace).

Future TODO: merge recordingstatus into recordingtypes?

### CODE REVIEW

**Comment by stuarta** [comment]
The service contracts all relate to the old webserver and we are working towards removing it and all the related QtScriptEngine code. As such we potentially do not even need to bother breaking this dependency, as we can just cleanup the code when we are happy with the replacement.

I'll need to do a more thorough review, but it looks like most of the changes here related to removing more stuff from libmyth into libmythbase?

This does have potential merit, but requires a thorough review.

**Comment by ulmus-scott** [comment]
> I'll need to do a more thorough review, but it looks like most of the changes here related to removing more stuff from libmyth into libmythbase?

That is correct.  I'm also planning on moving some of the GUI stuff in libmyth to libmythui and some recording* stuff from libmythtv to libmythbase.

**Comment by linuxdude42** [comment]
I like where this is going, but this change set is quite large (2000 lines) and there seem to be a number of unrelated changes here. This feels like it should be split into 4 or 5 smaller pull requests, so that each one is more focused. Maybe one for creating StringUtil and migrating the code to use the new functions, maybe one for the command line changes, definitely one that is solely related to the sorting changes, and then a couple more to set up and move the various sets of files between directories.

I am going to cherry-pick a handful of these commits that can stand on their own, and I have a few comments to add on individual commits. I hope this doesn't cause a problem for you.

**Comment by ulmus-scott** [comment]
> This feels like it should be split into 4 or 5 smaller pull requests, so that each one is more focused. Maybe one for creating StringUtil and migrating the code to use the new functions, maybe one for the command line changes, definitely one that is solely related to the sorting changes, and then a couple more to set up and move the various sets of files between directories.

It shouldn't be too difficult to split them.

- [ ] miscutil cleanup
  - [ ] miscellaneous
  - [ ] command line parser
  - [ ] string util
- [ ] sorting
- [ ] mythdate (probably depends on miscutil cleanup)
- [ ] move files
  - [ ] libmyth to libmythbase (this)
  - [ ] libmyth to libmythui
  - [ ] libmythtv to libmythbase
- [ ] bump library ABI version

**Comment by ulmus-scott** [comment]
fixup create mythrandom is now in https://github.com/MythTV/mythtv/pull/460

create mythpluginexport.h is now separate: https://github.com/MythTV/mythtv/pull/465

**Comment by ulmus-scott** [comment]
I'm of half a mind to drop [Fix translation calls](https://github.com/MythTV/mythtv/pull/438/commits/1444f321cdb69992125e3f81227f61b866026e38) and leave that for when all uses of QObject::tr() are replaced.

**Comment by ulmus-scott** [comment]
Apparently, moving the files to libmythui depends on https://github.com/MythTV/mythtv/pull/465.  The wonders of transitive includes (ugh).

**Comment by ulmus-scott** [comment]
Apparently, moving the files to libmythui depends on https://github.com/MythTV/mythtv/pull/465 .  The wonders of transitive includes (ugh).

**Comment by ulmus-scott** [comment]
I have dropped "fixing" the translation calls, which should be done in a different PR replacing all uses of QObject::tr() and updating the translation files accordingly.

I have also reincorporated https://github.com/MythTV/mythtv/pull/465 since moving the files to libmythui depends on it.

**Comment by bennettpeter** [comment]
I have not looked at the details  of the pull  request. However, the service API has been rewritten and everything in libmythservicecontracts can be removed. see programs/mythbackend/servicesv2 for the new code The old API is documented in https://www.mythtv.org/wiki/Services_API_Development_Guide.  THe conversion is documented in  https://www.mythtv.org/wiki/Services_API_V2_Conversion , The new API is documented in https://www.mythtv.org/wiki/Services_API_V2_Development_Guide .

A task that now need to be undertaken is removing the old API code and the old incomplete web frontend.

**Comment by ulmus-scott** [comment]
The only commits that have not been merged are the last two, which move files from libmyth to libmythui.  I'll need to redo those in a new pull request.

**Pull request closed without merging**
