### PR TITLE
Fix macOS 11 Big Sur audio issues by updating to audo code from master

### PR DESCRIPTION
**Pull request by jhoyt4**
##### Checklist

- [X] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [X] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [X] code compiles successfully without errors
- [X] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [X] documentation added/updated/removed where necessary
- [X] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

### CODE REVIEW

**Comment by jhoyt4** [comment]
Associated with PR284: [https://github.com/MythTV/mythtv/issues/284](url)

**Comment by linuxdude42** [comment]
Instead of your changes from yesterday, can you try cherry-picking d0d9a4e0bc950b44a1065b879d696f6c2c395491 to see if that solves the problem. If not, try cherry-picking 5c180c616ba7be44bfcea354819c6dcab5013222 as well.

**Comment by jhoyt4** [comment]
Will do - and if successful I'll update my repo / the PR

**Comment by jhoyt4** [comment]
> Instead of your changes from yesterday, can you try cherry-picking [d0d9a4e](https://github.com/MythTV/mythtv/commit/d0d9a4e0bc950b44a1065b879d696f6c2c395491) to see if that solves the problem. 

no luck with that one.  Trying [5c180c6](https://github.com/MythTV/mythtv/commit/5c180c616ba7be44bfcea354819c6dcab5013222) now

**Comment by jhoyt4** [comment]
try cherry-picking [5c180c6](https://github.com/MythTV/mythtv/commit/5c180c616ba7be44bfcea354819c6dcab5013222)

That got it - cleaning up my git repo and the PR shortly.

**Comment by jhoyt4** [comment]
Sorry - didn't meant to close this (still learning github).  I've opened a new PR (289) with the fixes suggested above.

**Pull request closed without merging**
